# -*- coding: utf-8 -*-
"""model_building.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Nx0nGkHLk5WbFb9_YrJ4nI9bs-jb6CA
"""

import pandas as pd

df = pd.read_csv('/content/Salary Data.csv')

df

df.info()

df.isnull().sum

for column in df.columns:
    if df[column].dtype == 'object':  # Categorical columns
        df[column] = df[column].fillna(df[column].mode()[0])
    else:  # Numerical columns
        df[column] = df[column].fillna(df[column].mean())

print("Null values after imputation:")
print(df.isnull().sum())

from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
le = LabelEncoder()

# Apply LabelEncoder to all object (categorical) columns
for column in df.select_dtypes(include='object').columns:
    df[column] = le.fit_transform(df[column])

print("DataFrame after applying Label Encoding:")
print(df.head())

X = df.drop('Salary', axis=1)
y = df['Salary']

print("Independent variables (X) shape:", X.shape)
print("Dependent variable (y) shape:", y.shape)
print("\nFirst 5 rows of X:")
print(X.head())
print("\nFirst 5 values of y:")
print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Define the models to be evaluated
models = {
    'Linear Regression': LinearRegression(),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'Support Vector Machine': SVR(),
    'K-Nearest Neighbors': KNeighborsRegressor()
}

results = {}

# Loop through each model, train, predict, and evaluate
print("--- Model Evaluation Results ---")
for name, model in models.items():
    print(f"\nTraining {name}...")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # Evaluate the model
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)

    results[name] = {'R-squared': r2, 'MAE': mae, 'MSE': mse, 'RMSE': rmse}

    print(f"{name} R-squared: {r2:.4f}")
    print(f"{name} MAE: {mae:.2f}")
    print(f"{name} MSE: {mse:.2f}")
    print(f"{name} RMSE: {rmse:.2f}")

print("\n--- Summary of Model Performance ---")
for name, metrics in results.items():
    print(f"{name}:")
    for metric_name, value in metrics.items():
        print(f"  {metric_name}: {value:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Convert the results dictionary to a DataFrame for easier plotting
results_df = pd.DataFrame(results).T

plt.figure(figsize=(15, 10))

# R-squared plot
plt.subplot(2, 2, 1)
sns.barplot(x=results_df.index, y='R-squared', hue=results_df.index, data=results_df, palette='viridis', legend=False)
plt.title('Model R-squared Comparison')
plt.ylabel('R-squared')
plt.xlabel('Model')
plt.xticks(rotation=45, ha='right')

# MAE plot
plt.subplot(2, 2, 2)
sns.barplot(x=results_df.index, y='MAE', hue=results_df.index, data=results_df, palette='magma', legend=False)
plt.title('Model Mean Absolute Error (MAE) Comparison')
plt.ylabel('MAE')
plt.xlabel('Model')
plt.xticks(rotation=45, ha='right')

# MSE plot
plt.subplot(2, 2, 3)
sns.barplot(x=results_df.index, y='MSE', hue=results_df.index, data=results_df, palette='plasma', legend=False)
plt.title('Model Mean Squared Error (MSE) Comparison')
plt.ylabel('MSE')
plt.xlabel('Model')
plt.xticks(rotation=45, ha='right')

# RMSE plot
plt.subplot(2, 2, 4)
sns.barplot(x=results_df.index, y='RMSE', hue=results_df.index, data=results_df, palette='cividis', legend=False)
plt.title('Model Root Mean Squared Error (RMSE) Comparison')
plt.ylabel('RMSE')
plt.xlabel('Model')
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()



